name: beer_afternoon
description: A Flutter project for retrieving a randomly generated beer object.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  beer_repository:
    path: packages/beer_repository

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.0.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
