name: beer_repository
description: A Repository layer to abstract the data layer and facilitate communication with the bloc layer.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  random_data_api:
    path: ../random_data_api


dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.24.1
  flutter_lints: ^2.0.1