name: random_data_api
description: An API Client for the Random Data API used for the main Beer afternoon app.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.24.1
  flutter_lints: ^2.0.1